### ISSUE TITLE
Error with P3 B+

### ISSUE THREAD

**Issue by Pasqui1978** [stooged/PI-Pwn#1]
![photo_2024-05-09_19-00-52](https://github.com/stooged/PI-Pwn/assets/104250169/78da043e-f20e-46de-8957-d1a1ea043355)

**Comment by B-Dem** [comment]
Bro just look at the error 
You didnt installed scapy

**Comment by Pasqui1978** [comment]
...why was I convinced I had installed it? 🤦🏻‍♂️

**Comment by stooged** [comment]
scapy should have been installed when you ran install.sh

just ssh into the pi and run 

```sh 
sudo apt install python3-scapy
```
