### ISSUE TITLE
usb drive not mounted on commit c8b2911

### ISSUE THREAD

**Issue by alfky12** [stooged/PI-Pwn#100]
usb drive mounted fine until commit f601944
Using armbian and dietpi.

![Screenshot 2024-05-21 145816](https://github.com/stooged/PI-Pwn/assets/100685677/51434182-6a0e-4be4-8c51-655c397e4d1d)

**Comment by stooged** [comment]
ok i will test armbian

**Comment by stooged** [comment]
what hardware are you using?

**Comment by alfky12** [comment]
> what hardware are you using?

tv box with amlogic s905x cpu.
but now i'm already finish convert armbian to dietpi.
![Untitled](https://github.com/stooged/PI-Pwn/assets/100685677/2dd6e75b-5f7a-4750-8bed-1fcd5d9235a4)

**Comment by stooged** [comment]
testing armbian here the usb is mounting on boot.

**Comment by alfky12** [comment]
now I go back to commit f601944, and usb drive mounted fine.
![Untitled2](https://github.com/stooged/PI-Pwn/assets/100685677/f93a7c5d-9627-40cf-9320-df15b9f12921)

**Comment by alfky12** [comment]
fixed in commit b4ec8a9
Thankyou @stooged
