### ISSUE TITLE
Is the virtual usb gone?

### ISSUE THREAD

**Issue by Justme488** [stooged/PI-Pwn#104]
Hi. First of all, thank you for your work @stooged . I'm a little confused. Is the virtual usb gone, or is it disabled if a real usb is in the pi?

**Comment by stooged** [comment]
Yes the virtual disk file was removed,.
A physical usb drive in the pi is used now

https://github.com/stooged/PI-Pwn?tab=readme-ov-file#usb-pass-through-drive
