### ISSUE TITLE
Boot problem with updated version

### ISSUE THREAD

**Issue by Shad0w80** [stooged/PI-Pwn#106]
Hi @stooged, i'm getting this error with the current version:

![Error](https://github.com/stooged/PI-Pwn/assets/169529815/dd869915-98a1-4fb3-8f44-709ae4f2c31f)

I'm using an external SSD to boot the rpi If this helps.
Edit: The file 'devboot.sh' seems to be the culprit, i've never had problems with the previous releases, where that file was missing.

**Comment by stooged** [comment]
i can see what is going on the mount on boot routine is un mounting the usb drive for the os.
i will have to work on a solution for that.

for the mean time you can just edit devboot.sh and put `exit 0`  above the readarray line and it should cause it to exit the script

**Comment by stooged** [comment]
should be fixed now, just replace the devboot.sh and it should stop killing the os mount

**Comment by Shad0w80** [comment]
Yes, fixed. Thank you
