### ISSUE TITLE
USB pass-through clarification

### ISSUE THREAD

**Issue by spiffin** [stooged/PI-Pwn#108]
Thanks for all your work on this - it's really appreciated. I'm unclear on your instructions for the USB pass-through drive - can this be the same USB drive that contains goldhen.bin? or a separate (second) USB drive?

**Comment by Doyle4** [comment]
If you have a Raspberry Pi 4/400/5 and powered via PS4s USB, it has passthrough, if using lower, needs to be direct into PS4 USB.
