### ISSUE TITLE
Web Server Background

### ISSUE THREAD

**Issue by Doyle4** [stooged/PI-Pwn#109]
Not coded a Pi before, Im more a download and flash person.

How do I go about adding my own background image? Maybe also custom buttons, had a Google and most results come back as use CSS, but not php.

Thanks.

**Comment by stooged** [comment]
all php is used for is to run commands on the pi then parse those commands and print html to the document.

if you look at the php files you will see most of it is just html being printed using the print() function of php so you can edit that html code and php will print it.

**Comment by Doyle4** [comment]
Thanks
