### ISSUE TITLE
No Restart pppwn Raspberry ZeroW with usb adapter

### ISSUE THREAD

**Issue by Alfons-Hetler** [stooged/PI-Pwn#119]
First of all... Really great projekt. But one issue is still all the time... after complete pppwn the pi zewo w not detect that the ps4 restart or is not more online. Thats the reason why the pppwn not automaticly restart pppwn.

i try many linux arguments to find out which is working to detect the ps4 is no more online. But the problem is through the usb Lan adapter thinks all the time was online... maybe a ping solution can working.

Thanks.

**Comment by stooged** [comment]
unfortunately usb network adapters operate a little different to onboard ethernet so to make some features work you will need to modify the code to suit your specific setup.
