### ISSUE TITLE
 Raspberry Pi Zero 2 W with Ethernet

### ISSUE THREAD

**Issue by chronoss09** [stooged/PI-Pwn#12]
Can this work with this model too ?

https://fr.aliexpress.com/item/1005005919648945.html?spm=a2g0o.productlist.main.45.40d961858o2K4l&algo_pvid=72d9f2f3-6819-439d-891b-6d4969dc4d40&algo_exp_id=72d9f2f3-6819-439d-891b-6d4969dc4d40-22&pdp_npi=4%40dis%21EUR%2111.62%2111.04%21%21%2112.23%2111.62%21%402101e9ec17153966364588903e2bbe%2112000034854939009%21sea%21FR%21908207159%21&curPageLogUid=iY8TIEGU4Z2P&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by stooged** [comment]
i tested the zero2 with usb and it worked, the ethernet board should work too.

**Comment by chronoss09** [comment]
ok thanks !!!

for installation, it's only for Linux or we can use Windows too ?
