### ISSUE TITLE
Add own Payload - Not an issue.

### ISSUE THREAD

**Issue by Doyle4** [stooged/PI-Pwn#124]
Is it possible to add our own Payloads to launch at all editing below code? Id love for Fan Payload to be sent on launch.
![Screenshot 2024-05-26 at 15 37 33](https://github.com/stooged/PI-Pwn/assets/65953502/43ff49cc-900d-458d-9e39-f1c89907e9f3)

**Comment by stooged** [comment]
if you edit that code then goldhen wont launch, you need stage2 to to setup goldhen.

you could try and add a second inject routine after goldhen gets injected https://github.com/SiSTR0/PPPwn/blob/goldhen/stage2/stage2.c#L422
