### ISSUE TITLE
Doesn't work with PSPlay

### ISSUE THREAD

**Issue by phpandrew** [stooged/PI-Pwn#125]
I opened all the ports available (similar to Chiaki)

```2121,3232,9090,8080,12800,1337,987,9290-9299,9300-9309,8572```

Bypassing the pi will work with PSPlay and connect no problem. However, through the Pi it cannot connect.
I am able to register the console through the Pi, but attempting to stream will not work.

Thank you!

**Comment by stooged** [comment]
Cool.
