### ISSUE TITLE
filezilla; Error: Failed to retrieve directory listing

### ISSUE THREAD

**Issue by youss-taouil** [stooged/PI-Pwn#129]
when i try to connect to my raspberry pi with or without username/password and transfer mode set to `active`. the ftp server is enabled on my ps4.
can i please get some help
![image](https://github.com/stooged/PI-Pwn/assets/113359981/31add727-cdc7-4ae7-91b7-a6ffc5b4a569)

**Comment by youss-taouil** [comment]
nvm, figured out that i can just connect my ps4 to local network after it was pwnd :)

**Comment by ImAlwaysInFaMouS** [comment]
Just a side not; easier to use the site manager (add the pi server) that way you keep "active" connection once selected in the settings.
