### ISSUE TITLE
Refuses custom or Redownloads Stage2 payload

### ISSUE THREAD

**Issue by CaelThunderwing** [stooged/PI-Pwn#130]
was trying to get this working with PS4 Linux's 11.00 updated Payloads (because i just dont want to always drag out my laptop or reboot my Steamdeck into windows)

it does require the use of a Custom Stage2 payload, and have replaced it in the PI-Pwn/pppwn directory, but it always takes a little longer than it needs to and ends up just loading Goldhen anyway.

Not sure WHY its happening and it wouldnt be an issue if GoldHen's Binloader server wasnt broken AF currently.

**Comment by stooged** [comment]
PI-Pwn/pppwn is the folder the repo is cloned into not the folder it runs out of

if you want to make changes to the files you need to change them in /boot/firmware/pppwn

**Comment by Doyle4** [comment]
> was trying to get this working with PS4 Linux's 11.00 updated Payloads (because i just dont want to always drag out my laptop or reboot my Steamdeck into windows)
> 
> it does require the use of a Custom Stage2 payload, and have replaced it in the PI-Pwn/pppwn directory, but it always takes a little longer than it needs to and ends up just loading Goldhen anyway.
> 
> Not sure WHY its happening and it wouldnt be an issue if GoldHen's Binloader server wasnt broken AF currently.

You haven't changed the file as stated above.
Reason it seems slower is Stooged put a wait time on loading Goldhen.
