### ISSUE TITLE
Change PS4 shared connection DNS

### ISSUE THREAD

**Issue by Shad0w80** [stooged/PI-Pwn#131]
There's a way to change the ps4 dns using the shared connection between ps4 and rpi? I'm using usb adapter, so i have eth0 as internet interface and eth1 for communication through the devices. I tried to set rpi "Wired connection 1" dns (wich is the eth0 interface i guess) using the nmcli command but it doesn't work. 
My goal is set the Nomadic dns to be able redirecting the PS4 User guide to PPPwn Hosts.
Or better, would be amazing if @stooged could implement this in his script. 
Thanks in advance

**Comment by Shad0w80** [comment]
> Are you talking about being able to go to payload hosts in the userguide?

Yep

**Comment by sudoxyz** [comment]
I have made that possible in my pull request #137 , hopefully it will be committed soon
