### ISSUE TITLE
Access Pi's SD over FTP?

### ISSUE THREAD

**Issue by Doyle4** [stooged/PI-Pwn#132]
Is it possible to add/remove files from the Pi's SD card using FTP at all?
I can SSH but id like to swap files without the need of removing the SD card.

I have tried: 192.168.2.2:21 - 192.168.2.2:2121 - 192.168.2.1:21 -192.168.2.1:21 and the same again but using 2121/22/2222

Thanks

**Comment by stooged** [comment]
I will add options to install a ftp server and samba share for the pi

**Comment by Doyle4** [comment]
Amazing thank you.

**Comment by stooged** [comment]
the option to install a ftp server and samba server have been added.

if you are using raspberry pi os you will need to set the root account password which is normally blank.
the script will prompt you to set the password.
the ftp server uses the standard ports 21 and 20 and you log into it with `root` as the username and the password you set for the root account.

the samba share has no user/pass needed to access it and can be mounted using
`\\pppwn.local\pppwn`
or
`\\<PI IPADDRESS>\pppwn`

**Comment by Doyle4** [comment]
Thank you so much.

**Comment by Doyle4** [comment]
![Screenshot 2024-05-30 at 07 04 58](https://github.com/stooged/PI-Pwn/assets/65953502/47941dd9-ab14-4f73-8063-52fa36827e02)
Working great thank you! This has made it so much better.

Thanks again for your efforts.

**Comment by stooged** [comment]
I prefer the samba approach too and it wasnt much effort to add as i just copied the code from my ps5 pi server repo.

Payloads on the sd card would still need to be coded.
I will add a function to fallback to a payloads folder in the pppwn dir on the sd card if no usb drive with a payloads folder is found.

**Comment by Doyle4** [comment]
Never used samba before, but was easy and once setup my Mac now detects which is amazing.

No worries, no rush at all as the USB method is fine, was a little curious if would be possible in future.

**Comment by stooged** [comment]
you can load playloads out of the `/boot/firmware/PPPwn/payloads` directory now if no usb is found

**Comment by Doyle4** [comment]
Amazing, will test once I can.

Thanks again.
