### ISSUE TITLE
Can't FTP to PS4 (Wrong IP address)

### ISSUE THREAD

**Issue by mmcgr97** [stooged/PI-Pwn#135]
After successfully jailbreaking my PS4 with Pi-Pwn I can't ftp from my PC to my PS4 as my network is 192.168.1.xxx and my PS4 is on 192.168.2.2.

Is this normal? Do I need to switch to Wi-Fi and connect to my home network to ftp pkg files and then switch back to ethernet the next time I reboot the console?

**Comment by stooged** [comment]
https://github.com/stooged/PI-Pwn?tab=readme-ov-file#ftp--binload

**Comment by mmcgr97** [comment]
OK I've connected to the IP of the Pi but it won't show the contents of the PS4, only the Pi.

**Comment by mmcgr97** [comment]
How do I access the contents of the PS4 hard drive through the Pi in FTP on PC?
