### ISSUE TITLE
FTP to PS4 through Pi

### ISSUE THREAD

**Issue by mmcgr97** [stooged/PI-Pwn#138]
Does anyone know how I can access the contents of the PS4 hard drive when FTPing to the Pi over Wi-Fi?

The main page says

"To connect to the servers from your pc just connect to the raspberry pi ip on your network and all requests will be forwarded to the console"

I've connected to the Pi in Filezilla but I'm only seeing the contents of the Pi, not the PS4 hard drive.

Both FTP Server and BinLoader Server (not sure what that is) are enabled.

**Comment by sudoxyz** [comment]
make sure you are using port 2121 and that the transfer mode is active

**Comment by Doyle4** [comment]
No method has ever worked for me so far for FTP, Active or Passive enabled/disabled.

Im using a Mac.

**Comment by Shad0w80** [comment]
> Does anyone know how I can access the contents of the PS4 hard drive when FTPing to the Pi over Wi-Fi?
> 
> The main page says
> 
> "To connect to the servers from your pc just connect to the raspberry pi ip on your network and all requests will be forwarded to the console"
> 
> I've connected to the Pi in Filezilla but I'm only seeing the contents of the Pi, not the PS4 hard drive.
> 
> Both FTP Server and BinLoader Server (not sure what that is) are enabled.

https://github.com/stooged/PI-Pwn/issues/83
