### ISSUE TITLE
Remote Play not working when using dual ethernet setup

### ISSUE THREAD

**Issue by ThatGuyTrav** [stooged/PI-Pwn#144]
I've port forwarded and cant get the ps4 to register with Chiaki. Is there anything else I'm missing or does remote play not work with Pi-Pwn currently on a daul ethernet setup?

**Comment by stooged** [comment]
i will have to test it but the only interface specific part should be the one the console is connected to, everything else should be routed.

**Comment by stooged** [comment]
tested it with an onboard ethernet port and usb to ethernet adapter and everything works the same as eth+wifi
