### ISSUE TITLE
Could u support Orange Pi model, Please

### ISSUE THREAD

**Issue by Scientistpsy** [stooged/PI-Pwn#145]
Could u support Orange Pi model, Please. 
Previous- pi pwn -version was tested on Orange pi zero3 1g with debian ISO, and it was working great, but with the new update scarcely works the hack.

**Comment by shoyrock** [comment]
I should work from what I've tested on some arm devices that are not tested as tested, and they work fine. I tested the NanoPi R5 nano pi neo3, using dietpi and some other Debian. and Armbian works without any problem
