### ISSUE TITLE
It stays at the Ready for console connection

### ISSUE THREAD

**Issue by HalaraMan** [stooged/PI-Pwn#15]
It stays there without proceeding, even going to the check network on ps4 it dosent do anything. 
Running this:
`sudo python3 /boot/firmware/PPPwn/pppwn.py --interface=$INTERFACE --fw=$FIRMWAREVERSION --stage1=/boot/firmware/PPPwn/pppwn.bin --stage2=/boot/firmware/PPPwn/stage2_$FIRMWAREVERSION.bin` 

it shows this error:
`usage: pppwn.py [-h] --interface INTERFACE [--fw {900,1100,9.00,11.00}]
                [--stage1 STAGE1] [--stage2 STAGE2]
pppwn.py: error: argument --fw: invalid choice: '' (choose from '900', '1100', '9.00', '11.00')
`
I am using a Raspberry Pi 3 b+
Do you have any idea why its doing this?

**Comment by stooged** [comment]
i have made some changes to deal with slower rpi models not starting the pppwn properly.
