### ISSUE TITLE
the new update shows end0 and detects dummy interface

### ISSUE THREAD

**Issue by kuraimangetsu** [stooged/PI-Pwn#159]
hi
the new update i tested with armbian img detects dummy LAN interface instead of eth0 and there is no eth0
only end0
the last update shows eth0 fine and works fine

**Comment by stooged** [comment]
Armbian uses end0 not eth0.
The detected interfaces are a list of interfaces on the device from ip link.

If you want to set a specific address you can manually enter it during the install or you can edit config.sh
