### ISSUE TITLE
Orange Pi Zero 2W

### ISSUE THREAD

**Issue by el-quique** [stooged/PI-Pwn#16]
Hello. When trying to compile on an Orange Pi Zero 2W it gives me a syntax error:
gcc    -c -o start.o start.S
start.S: Mensajes del ensamblador:
start.S:8: Error: pseudo-operador desconocido: «.intel_syntax»
start.S:16: Error: mnemónico inválido `call' -- `call stage1'
start.S:19: Error: operando 1 debe ser an integer register -- `mov rsp,rbx'
start.S:20: Error: operando 1 debe ser an integer or stack pointer register -- `sub rsp,(0x88+0x38)'
start.S:23: Error: operando 1 debe ser an integer or stack pointer register -- `add rsp,8'
start.S:24: Error: mnemónico inválido `pop' -- `pop rbx'
start.S:25: Error: mnemónico inválido `pop' -- `pop r12'
start.S:26: Error: mnemónico inválido `pop' -- `pop r13'
start.S:27: Error: mnemónico inválido `pop' -- `pop r14'
start.S:28: Error: mnemónico inválido `pop' -- `pop r15'
start.S:29: Error: mnemónico inválido `pop' -- `pop rbp'

What would I have to modify to be able to compile?
Thank you so much

**Comment by stooged** [comment]
i cant help with the orange pi as i dont have one to test with sorry
