### ISSUE TITLE
Roseberry PI

### ISSUE THREAD

**Issue by IRONB0SS** [stooged/PI-Pwn#161]
Hey Sir, Can I use Raspberry Pi 4B 4G?
![Screenshot_20240706_232907_Samsung Internet.jpg](https://github.com/stooged/PI-Pwn/assets/97769328/1dcf3701-ff03-4bc5-8c60-31a82b086b7c)

**Comment by stooged** [comment]
https://github.com/stooged/PI-Pwn?tab=readme-ov-file#tested-pi-models
