### ISSUE TITLE
Beta for Problem Model

### ISSUE THREAD

**Issue by Jorge07-07** [stooged/PI-Pwn#164]
Is it possible to have C++ Beta CPP 0616 for problem models on the Raspberry Pi?

**Comment by stooged** [comment]
not sure what "C++ Beta CPP 0616" is supposed to be but i will assume you are talking about models of ps4 that were unable to pwn until the ipv6 address was modified.

by default pi-pwn uses the modified address for problematic consoles with an option to switch back to the original.

**Comment by Jorge07-07** [comment]
> not sure what "C++ Beta CPP 0616" is supposed to be but i will assume you are talking about models of ps4 that were unable to pwn until the ipv6 address was modified.
> 
> by default pi-pwn uses the modified address for problematic consoles with an option to switch back to the original.

Even with IPv6 I can only unlock my console by switching to the beta version that PSGO introduced in its application. Otherwise, it keeps trying to unlock without success.
https://github.com/PSGO/PPPwn-Lite/releases/tag/v5.6
