### ISSUE TITLE
network sharing issue

### ISSUE THREAD

**Issue by epiclulz666** [stooged/PI-Pwn#165]
I'm using a Raspberry Pi 4 with Raspberry Pi Lite 64-bit installed. I've connected a USB-A to Gigabit adapter from my PS4 Pro to the Raspberry Pi 4, and I'm using Pi-Pwn for jailbreaking. The jailbreak interface is set to eth1, and I've successfully set up internet sharing. I can browse the web and perform internet activities on the PS4 using an Ethernet cable connected to a switch that's linked to the Pi's main Ethernet port.

However, my issue is that internal functions aren't working as expected. I've enabled the FTP server in GoldHEN, and from a PC on my network, I attempt to connect to the Pi's IP address on port 2121. It shows that the connection is established but doesn't display any directories. Although I can ping and SSH into the Pi, the remote package sender (which operates on port 12800, i also added the servers port of 8337 ) this also doesn't work. When I use the test button in the app, it reports that it can't find the PS4.

I tried adding routes into iptables based on suggestions I found, but this hasn't resolved the issue either i disabled windows firewall no luck. Do you have any suggestions on how to troubleshoot or fix this problem?

```
Status:	Connecting to 192.168.1.172:2121...
Status:	Connection established, waiting for welcome message...
Status:	Insecure server, it does not support FTP over TLS.
Status:	Server does not support non-ASCII characters.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is the current directory.
Command:	TYPE I
Response:	200 Command okay.
Command:	PASV
Response:	227 Entering Passive Mode (192,168,2,2,196,184).
Command:	MLSD
Response:	150 File status okay; about to open data connection.
Error:	Connection timed out after 20 seconds of inactivity
Error:	Failed to retrieve directory listing
```

**Comment by epiclulz666** [comment]
<img width="792" alt="Screenshot_7" src="https://github.com/user-attachments/assets/110f190d-f53b-477d-ade6-4708a10542d1">

**Comment by stooged** [comment]
https://github.com/stooged/PI-Pwn?tab=readme-ov-file#console-ftp--binload
