### ISSUE TITLE
CUH-2216A - 2116A - 2016B  and Models not working 

### ISSUE THREAD

**Issue by imabou** [stooged/PI-Pwn#167]
I tested with this console with the ipv6 flag On and the console crashes in the middle of operation .

**Comment by Tope1963** [comment]
I have a PS4 slim 11.00 version CUH - 2016B and I'm using a Pi zero 2 w configuration according to the MODDED WARFARE video.
After several attempts the ps4 turns off.
Is it true that this method does not work in these versions?
