### ISSUE TITLE
Connect PC to ps4 through FTP after pppoe connection

### ISSUE THREAD

**Issue by sudoxyz** [stooged/PI-Pwn#17]
would this be possible?
currently, I have my PC and Pi hooked up to a network switch, the pi has its main eth and an adapter to the switch
would it be possible to connect to the PS4's FTP server without needing another adapter?

**Comment by stooged** [comment]
yes

i will add the tables for it in the morning and the binloader

**Comment by stooged** [comment]
i ended up adding them before going to bed.

once everything is loaded enable the ftp server in goldhen. 
set the ftp clients transfer mode to `Active` 
then use your ftp client to connect to the raspberry pi ip address on your network and ftp should load to the console.
