### ISSUE TITLE
with latest update the playstation does not get a IP from pppwn

### ISSUE THREAD

**Issue by bse4792** [stooged/PI-Pwn#170]
Hi.

been using your software for some time with good success, but after some updates, its not running.

info from PPPwn++ display
raspberry pi 1 model B rev 1.1
firmware 11.00
interface eth0
PPPwn: C++ pppwn7
internet access: enabled
waiting for link
link found

then nothing else happens the PS4 does not get an ip i had the same issue with first gen jailbreak

**Comment by Doyle4** [comment]
Some PS4s need the new IP address, some don't, its worth testing each to see which is most successful.
JB after updating can make the process a little longer, give it a good 5mins, after 1st JB success it usually is quicker from then on.
