### ISSUE TITLE
Options usage issue

### ISSUE THREAD

**Issue by adiltanvir** [stooged/PI-Pwn#172]
There is no way to use options mentioned during the installation. For example to use the the old ipv6 ip for improving performance. Add a way to use options that you had mentioned inside your Readme file.

**Comment by Doyle4** [comment]
> There is no way to use options mentioned during the installation. For example to use the the old ipv6 ip for improving performance. Add a way to use options that you had mentioned inside your Readme file.

You're doing something wrong, the options/settings when setting up always show in the terminal, once setup the options are there also on the landing page.
