### ISSUE TITLE
PPPwn stuck on waiting for PADI after a failed attempt on latest RPi OS version.

### ISSUE THREAD

**Issue by ThatGuyTrav** [stooged/PI-Pwn#175]
I'm unsure about other models but for me on the Raspberry Pi 4 if PPPwn has a failed attempt, it gets stuck on waiting for PADI. It seems the latest release of RPi OS Lite (2024-07-04) causes this to happen. The previous release (2024-03-15) seems to keep retrying automatically with no issues.

**Comment by stooged** [comment]
i tested 2024-07-04 (64bit) on a pi 4 and it works the same as other versions of the lite os.
