### ISSUE TITLE
[REQUEST] add needed ports to use chiaki by default

### ISSUE THREAD

**Issue by loddi-o** [stooged/PI-Pwn#178]
To use chiaki (or remote play i guess) by you pi internet connection, you must open some ports in the pi-pwn interface accessible by typing your pi ip in the browser. The ports are: 
```
987
9295
9296
9297
9302
9303
9304
9305
```
It would be nice if they were opened by default

**Comment by stooged** [comment]
the main reason i added the option for people to add ports was so they could pick and choose what they want, once you save the ports they remain until you remove them, delete ports.txt or format the sd card in the pi.

i left the default ports at a minimum for goldhen.
