### ISSUE TITLE
how to run on regular pc?

### ISSUE THREAD

**Issue by W-i-n-7** [stooged/PI-Pwn#179]
hi i dont have a raspberry pi and getting one would be difficult for me im looking to deticate a laptop to run PPPwn automatically would be really nice

**Comment by micaslarsen** [comment]
Then don't use this fork dedicated for running on a Pi.
I'd look at foolproof GUI solutions instead: [PPPwn-Lite](https://github.com/PSGO/PPPwn-Lite/releases) or [PPPwnGo](https://github.com/PSGO/PPPwnGo/releases)

**Comment by W-i-n-7** [comment]
oh i did not know they can run unattended
