### ISSUE TITLE
can not change ppp/ppp

### ISSUE THREAD

**Issue by isty1974** [stooged/PI-Pwn#181]
At installing you choose N, it will write use deafult ppp/ppp. Where can I change it to any other? ie..: to  g/g

**Comment by DavidLeBonk** [comment]
If I'm not mistaken this can (currently) only be set during install.

**Comment by isty1974** [comment]
That would nice on admin screen can be chane user name and psw as well. Thx
Ps. where can I find it after installation, to midofy it?

**Comment by stooged** [comment]
added a button on the web ui "Network Settings" which will allow you to change the pppoe server info
