### ISSUE TITLE
Changed PS4 firmware version after initial PI-Pwn setup - do i need to change a setting in the Pi?  Not "succeeding" after firmware updated to 11.0

### ISSUE THREAD

**Issue by cbjfan2009** [stooged/PI-Pwn#182]
My initial RPi setup, I told PI-Pwn that I was on 10.50.  After success, but no GoldHEN access, I updated firmware to 11.00 to be in-line with "the standard in all the guides and tutorials."

Now, I just get PS4 crash after crash.  Do I need to edit some configuration to let the Pi-Pwn script target 11.00 firmware instead of 10.50?

Maybe this can be deleted.  I interrupted the script and went back to command and re-installed using 11.00 at the prompt. 
However, no I'm hung up on "Link Found" permanently.

**Comment by Doyle4** [comment]
Power the pi and access it via web broswer, change the config to 11.00 from 10.50

**Comment by stooged** [comment]
re run the install commands used to install pi-pwn and change the settings or use the web ui to change them.
