### ISSUE TITLE
Add Raspberry 1 model B to list

### ISSUE THREAD

**Issue by rui-costa** [stooged/PI-Pwn#187]
Tested with a Raspberry Pi 1 and it works perfectly.
![2024-09-09-17-43-14-110.jpg](https://github.com/user-attachments/assets/b0b11eff-457f-434d-9a44-38ab2ac61a6c)

**Comment by donnyad** [comment]
issue is if you use passthrough or "network bridge" for allowing automatic wifi share. then youll be limited to the raspberry pi 1s low internet compatability.
