### ISSUE TITLE
Add Orange Pi One support, works fine

### ISSUE THREAD

**Issue by dejanivicic** [stooged/PI-Pwn#188]
Orange Pi One with just 512MB runs great with PS4 Pro
http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-One.html

**Comment by Doyle4** [comment]
Only added if Stooged himself tests.

**Comment by stooged** [comment]
the list in the readme is just a list of boards i have personally tested, its not a list of "supported" boards as you can run it on many different types of hardware.
