### ISSUE TITLE
Need UPDATE pppwn2

### ISSUE THREAD

**Issue by ehackingar** [stooged/PI-Pwn#190]
Hello 
Thank you for the Great work 
we need Update pppwn2 fix crashs and rebooting ...
thank you

**Comment by 1234abd** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by ehackingar** [comment]
@1234abd  keep thinking for another  way to help 
 just keep away from this community
