### ISSUE TITLE
pppwn64 binary not working on Raspberry Pi 3b

### ISSUE THREAD

**Issue by piterq** [stooged/PI-Pwn#21]
pppwn64 does nothing on Raspberry Pi 3b. When launched directly form console it gives no output.

**Comment by piterq** [comment]
UPDATE: pppwn binary from https://nightly.link/xfangfang/PPPwn_cpp/workflows/ci.yaml/main/aarch64-linux-musl.zip seems to be working fine.

**Comment by stooged** [comment]
i tested it on my 3b+ and it worked.

the compilation target was aarch64-linux-musl and it was modified to give no output to be used with pi pwn which is why you see no output.
