### ISSUE TITLE
C++ version confirmed working on raspberry Pi 2 model B

### ISSUE THREAD

**Issue by bbossink** [stooged/PI-Pwn#22]
See title.....fast response (ca 30-45sec between each attempt) from Pi2 model B. 4th attempt successfull
You can add it to you're Readme ;-)
Many Thanks!!!

**Comment by nedjoni** [comment]
I can confirm this can work with Pi 1 B+.
It works nicely under (legacy 32 bit) Debian Bullseye lite version of Raspbery Pi OS.
The only difference is path: PPPwn folder is not under /boot/firmware/, but under the /boot/ folder, itself, so it needs to be changed in all the instances of the install.sh code.
Also, Pi 1 B+ doesn't have a WiFi, so the only available interface port is eth0.

**Comment by DjPopol** [comment]
> I can confirm this can work with Pi 1 B+. It works nicely under (legacy 32 bit) Debian Bullseye lite version of Raspbery Pi OS. The only difference is path: PPPwn folder is not under /boot/firmware/, but under the /boot/ folder, itself, so it needs to be changed in all the instances of the install.sh code. Also, Pi 1 B+ doesn't have a WiFi, so the only available interface port is eth0.

Use usb adapter
