### ISSUE TITLE
Adding support for 10.71 firmware

### ISSUE THREAD

**Issue by pemre** [stooged/PI-Pwn#23]
Thank you for the tool! Is there an easy way to support 10.71? If so, I'd like to contribute!

**Comment by NukleonPL** [comment]
You can easily make the update to 11.00: 
https://darksoftware.xyz/PS4/FWlist

**Comment by stooged** [comment]
goldhen does not support other firmwares yet, it only supports 9.00 and 11.00.
once it is updated support for those firmwares will be added.
