### ISSUE TITLE
GoldHen - ftp server 

### ISSUE THREAD

**Issue by Puky70** [stooged/PI-Pwn#26]
I have followed your installation guide and my internet is working. Under View Connection status following IP will be shown like in your video at 03:10 minutes. It is possible to change the bridge function to local network? I want to access the PS4 from my computer via GH ftp server ;-)

**Comment by stooged** [comment]
you access ftp by connecting to the raspberry pi's ip address on your network.
ignore the ip that goldhen prints, you connect to the pi and the pi will route the traffic to the console.

set your ftp client transfer mode to active, passive does not work.

**Comment by Puky70** [comment]
Thanks! It is working fine now.

**Comment by mjchrisu** [comment]
You mean i have to use the WLAN IP address from the Pi, and Port 2121?
I am trying Filezilla, but cant connect.

**Comment by mjchrisu** [comment]
> you access ftp by connecting to the raspberry pi's ip address on your network. ignore the ip that goldhen prints, you connect to the pi and the pi will route the traffic to the console.
> 
> set your ftp client transfer mode to active, passive does not work.
> 
> you will probably need to enable the ftp server in goldhen after the pppwn completes. there is no way to delay goldhen starting the server and it starts it too fast so the ftp does not setup properly.

You mean i have to use the WLAN IP address from the Pi, and Port 2121?
I am trying Filezilla, but cant connect.

**Comment by stooged** [comment]
> 
> You mean i have to use the WLAN IP address from the Pi, and Port 2121? I am trying Filezilla, but cant connect.

i just updated run.sh, trying to forward all ports was messing with it so i reverted back to just the ftp, binload and klog ports.

**Comment by mjchrisu** [comment]
> > You mean i have to use the WLAN IP address from the Pi, and Port 2121? I am trying Filezilla, but cant connect.
> 
> i just updated run.sh, trying to forward all ports was messing with it so i reverted back to just the ftp, binload and klog ports.

It still does not work. But i can open www.google.com on PS4.

**Comment by stooged** [comment]
what are the messages filezilla is posting

**Comment by mjchrisu** [comment]
> what are the messages filezilla is posting

PWD
257 "/" is the current directory.
TYPE I
200 Command okay.
PORT 10,0,0,1,205,242
200 Command okay.
MLSD
150 File status okay; about to open data connection.

**Comment by stooged** [comment]
set the transfer mode to active
![active](https://github.com/stooged/PI-Pwn/assets/9004083/8718e203-dd84-4d0d-8714-f19e643527d2)
