### ISSUE TITLE
Crash of PS4 slim with fw 11.0 using a Raspberry Pi 3B+

### ISSUE THREAD

**Issue by Ul7iMaTeG3MiNi** [stooged/PI-Pwn#31]
I have a PS4 slim with fw 11.0 and for pppwn via Raspberry I used a Raspberry Pi 3B+ and an ethernet cable without any adapter. During the installation procedure there is no problem, but when the console is about to be jailbroken the PS4 turns off, any ideas or solutions?

**Comment by un4ckn0wl3z** [comment]
> I have a PS4 slim with fw 11.0 and for pppwn via Raspberry I used a Raspberry Pi 3B+ and an ethernet cable without any adapter. During the installation procedure there is no problem, but when the console is about to be jailbroken the PS4 turns off, any ideas or solutions?

Is it always happening? For me it's occur this problem once, but this problem gone after second try.

**Comment by stooged** [comment]
i have tested with my pi 3b+ both 64bit and 32bit os and it works so i am not sure what to suggest.

maybe try change the os, you you are on 64 then try 32.
