### ISSUE TITLE
100% CPU usage for pppwn64

### ISSUE THREAD

**Issue by alfky12** [stooged/PI-Pwn#33]
Is this normal when waiting for console connection and during the jailbreak process?
Using C++ method.

![Screenshot (185)](https://github.com/stooged/PI-Pwn/assets/100685677/5fa65b08-a1d7-40d4-aaba-574d27aa8c8b)

**Comment by stooged** [comment]
pppwn64 is the compiled bin for the [PPPwn_cpp](https://github.com/xfangfang/PPPwn_cpp) project.
if it has a high cpu usage then it will be due to how that is coded.

**Comment by stooged** [comment]
issue has been resolved in last update.
