### ISSUE TITLE
Waiting for link obstructive when trying to run terminal commands

### ISSUE THREAD

**Issue by Sylntnyt** [stooged/PI-Pwn#35]
The "link detection" block of code addition to run.sh causes the "waiting for link" message to repetitively print on screen and become obstructive while trying to utilize the terminal to run install.sh or any other tasks with the console off and Ethernet cable plugged in or even unplugged. Perhaps if there was a way to have it print the one time and wait indefinitely without printing again when other input/output is being performed, or halt when the user interrupts the process to log into and use the terminal. Not a huge issue, more of an annoyance/inconvenience or bug that can make changing parameters using install.sh after initial setup a bit of a pain especially if one is not familiar with the questions being asked along with the acceptable responses or access to a computer to modify config.sh.

**Comment by stooged** [comment]
i will change it, thanks for the feedback
