### ISSUE TITLE
Remote Package Sender

### ISSUE THREAD

**Issue by Akirainblack** [stooged/PI-Pwn#38]
Hello,
I use remote package sender/remote package installer to install pkg.
`https://github.com/flatz/ps4_remote_pkg_installer`
However it isn't currently working with the pass through from my Pi to the PS4.
I can access the internet on the PS4 but can't send packages to it.
Is this something you might consider fixing, please?

Thank you,

**Comment by waterfallm** [comment]
should just be a case of passing through port 12800 to the PS4 and readme update to let people know to use the PI ip and not the PS4

**Comment by waterfallm** [comment]
@stooged I'm happy to raise PR if you can give me perms.

**Comment by waterfallm** [comment]
maybe running the command manually on PI will also work



`sudo iptables -t nat -I PREROUTING -p tcp --dport 12800 -j DNAT --to 192.168.2.2:12800`

**Comment by Akirainblack** [comment]
@waterfallm just tried that now. Worked PERFECTLY, thank you!

Will it persist through a reboot?

**Comment by stooged** [comment]
added routing table for it
