### ISSUE TITLE
PPPwn launches but stuck on ready for console connection 

### ISSUE THREAD

**Issue by LifeOfAScoob** [stooged/PI-Pwn#4]

**Comment by DjVreditel** [comment]
Problem in the commented IPv6 recognition lines, in this script author commented a lot of them 😄

**Comment by PereProteus** [comment]
If anyone see this, I loaded up this image without any changes or file uploaded needed and it just worked and GoldHen loaded up. https://github.com/CrazeeGhost/PS4JbEmu/releases/tag/v3.0-b1

**Comment by silvioinpixels** [comment]
> If anyone see this, I loaded up this image without any changes or file uploaded needed and it just worked and GoldHen loaded up. https://github.com/CrazeeGhost/PS4JbEmu/releases/tag/v3.0-b1

It keeps restarting PS4 on the final stage, not working

**Comment by jasii** [comment]
> > If anyone see this, I loaded up this image without any changes or file uploaded needed and it just worked and GoldHen loaded up. https://github.com/CrazeeGhost/PS4JbEmu/releases/tag/v3.0-b1
> 
> It keeps restarting PS4 on the final stage, not working

Weird, it worked for me within 5 mins, PS4 pro. This stooged version didn't work at all. It's just sit for hours.
