### ISSUE TITLE
Error creating USB in latest build.

### ISSUE THREAD

**Issue by Akirainblack** [stooged/PI-Pwn#41]
Last step of the install script followed by immediate error. - There is a 128GB microSD in the Pi4 B.
Do you want the pi to act as a flash drive to the console

(Y|N)?: y
dd: error writing '/boot/firmware/PPPwn/pwndev': No space left on device
48364+0 records in
48363+0 records out
198094848 bytes (198 MB, 189 MiB) copied, 0.868351 s, 228 MB/s
mkfs.fat 4.2 (2021-01-31)
dtoverlay=dwc2
mkdir: cannot create directory ‘/media/pwndev’: File exists
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
cp: cannot stat '/root/PI-Pwn/USB Drive/goldhen.bin': No such file or directory
The pi will mount as a drive and goldhen.bin has been placed in the drive
You must plug the pi into the console usb port using the usb-c of the pi
#!/bin/bash
INTERFACE="eth0"
FIRMWAREVERSION="9.00"
SHUTDOWN=false
USBETHERNET=false
USECPP=true
PPPOECONN=true
VMUSB=true
rm: cannot remove '/usr/lib/systemd/system/bluetooth.target': No such file or directory
rm: cannot remove '/usr/lib/systemd/system/network-online.target': No such file or directory
[Service]
WorkingDirectory=/boot/firmware/PPPwn
ExecStart=/boot/firmware/PPPwn/run.sh
Restart=never
User=root
Group=root
Environment=NODE_ENV=production
[Install]
WantedBy=multi-user.target
Install complete, Rebooting

Broadcast message from root@PPPwn on pts/3 (Tue 2024-05-14 14:21:04 BST):

The system will reboot now!

Broadcast message from root@PPPwn on pts/3 (Tue 2024-05-14 14:21:04 BST):

The system will reboot now!

Of note my user account isn't root, which is possibly why it's not finding the USB Drive folder?

**Comment by stooged** [comment]
i did get the space error once using armbian so i might move the file for the virtual drive out of the boot folder to the home folder.

you can put a usb flash drive into the pi and it should mount that instead of the virtual drive.

**Comment by stooged** [comment]
it should be working properly now.
