### ISSUE TITLE
Need help with understanding the code

### ISSUE THREAD

**Issue by Andryshik345** [stooged/PI-Pwn#45]
Hello, I'm trying to adapt your run.sh script for Alpine Linux. And I can't understand what `coproc read -t 15 && wait "$!" || true` does? What the purpose of it?

Since Alpine doesn't have Bash, I need either to remove it or make some workaround.

**Comment by stooged** [comment]
It is a way of pausing the thread without causing high cpu usage.

The `-t 15`variable is the wait time in seconds.

Replace it with `sleep 15`  or what ever the equivalent is in alpine to make the thread wait.

**Comment by Andryshik345** [comment]
Alright, but what is the purpose of pausing it in the first place?
