### ISSUE TITLE
 There is compatibility with TV Box mxq pro 4k - rk3228a with armbian for rk322x confirmed by me.

### ISSUE THREAD

**Issue by Reserxd** [stooged/PI-Pwn#52]
There is compatibility with TV Box mxq pro 4k - rk3228a with armbian for rk322x confirmed by me.

https://drive.google.com/file/d/1jQQ9uLjPpFN3-Il2Do7yAOvfjVHOcGr8/view?usp=sharing
https://drive.google.com/file/d/1gi0p3Vh63H1MKMWXncUrw4U6dqyvuJ4J/view?usp=sharing

**Comment by Doyle4** [comment]
Nice

**Comment by ravzkie12** [comment]
Hello, Did it work to inject code into PS4?

**Comment by Reserxd** [comment]
> Hello, Did it work to inject code into PS4?

Yes
