### ISSUE TITLE
hibernate

### ISSUE THREAD

**Issue by damaskuss** [stooged/PI-Pwn#53]
After you send the console to sleep, Raspberry wakes up and works

**Comment by DerDom2010** [comment]
I solved this by doing a cronjob that sends, in my case the NanoPi NEO, to shutdown after 10 Minutes.

**Comment by tristan-k** [comment]
@DerDom2010 off-topic: Do you use a usb-ethernet adapter for the second nic? I'm searching for a cheap sbc with dual ethernet or one ethernet and the possibilty to attach a usb ethernet adapter for pi-pwn. Ideally it could be powered through the usb ports of the ps4. I want to use chiaki for remote play so a second nic is a priority for me.

The NanoPi R1 so far seems to be the best fit but the NanoPi NEO is cheaper. Any thoughts?
