### ISSUE TITLE
[ShowCase]Perfect on rpi2b+ with spi screen

### ISSUE THREAD

**Issue by milesking** [stooged/PI-Pwn#57]
<img width="657" alt="截屏2024-05-16 09 01 39" src="https://github.com/stooged/PI-Pwn/assets/16441294/5f4a9ccf-4a5c-4609-80ec-95a231f1c5f6">

**Comment by Rocket200** [comment]
@mileskin what you change on Pi2 to get the Screen running ? Or PI-PWN Code ?
Looks nice 👍 
Please show how you do this 
Thanks

**Comment by milesking** [comment]
> @mileskin what you change on Pi2 to get the Screen running ? Or PI-PWN Code ? Looks nice 👍 Please show how you do this Thanks

You don't have to touch the PI-PWN project code at all. Just plug in an SPI screen to your Raspberry Pi and get that console driver working, and you're all set.
