### ISSUE TITLE
Not an issue, update on ssh 

### ISSUE THREAD

**Issue by Doyle4** [stooged/PI-Pwn#58]
If you add the new Web server, your ssh name is changed, mine changed from pppwnpi.local to pppwn.loca.
So if you can't connect via shh, try ssh pppwn.local.

I thought I had messed something up during update, so hopefully helps others.

Also, is it possible for the PS4 to have internet via the Pi? I see others have, but my PS4 thinks its offline.

**Comment by stooged** [comment]
the pppwn hostname change was intentional so the pi and console can be accessed using `http://pppwn.local` and the console has internet access.

you need to allow internet access during setup and use the pppoe username and password set there in the console pppoe settings.

**Comment by Doyle4** [comment]
Got you!! Thank you very much!
