### ISSUE TITLE
RemotePlay Access

### ISSUE THREAD

**Issue by pinxamoreno** [stooged/PI-Pwn#62]
PSPlay and Chiaki can´t  find the PS4 when it is connected to the Raspberry pi. I did also try to add the ports 9295,9296,9297,9303,9304,987,8572 but nothing. Is there any special settings to set in the tools or in the pi or it is just not working yet?

**Comment by SteveMac555** [comment]
RemotePlay uses a combination of TCP and UDP ports, pppoe.sh currently is only adding TCP to iptables. You may need to alter this to get remote play working

**Comment by stooged** [comment]
changed it to forward both udp and tcp
