### ISSUE TITLE
Remote play

### ISSUE THREAD

**Issue by Musicislife6984** [stooged/PI-Pwn#66]
Cannot connect remote play when sharing the internet via raspberry pi

**Comment by ImAlwaysInFaMouS** [comment]
Its not set up to allow connections on the right ports. Could try:

(TCP)
sudo iptables -t nat -I PREROUTING -p tcp --dport 9295 -j DNAT --to 192.168.2.2:9295
(UDP)
sudo iptables -t nat -I PREROUTING -p tcp --dport 9296 -j DNAT --to 192.168.2.2:9296

?
