### ISSUE TITLE
Raspberry Pi Suggestion - Also confirming that Pi-Pwn works on Raspberry Pi 3 B as well.

### ISSUE THREAD

**Issue by MiToRMK** [stooged/PI-Pwn#69]
Hi Stooged - I have a suggestion, would you consider adding an option to the webserver so we can control, or dim, the frontal LED on the Pi? It is super bright, red light, and of course the LED remains on even with the Pi turned off (after PPPwn). I am using a Raspberry Pi 3B in my setup:

![Image from iOS](https://github.com/stooged/PI-Pwn/assets/53503644/e6f0fe0c-59aa-404d-b9cf-b747827e9bc6)

The light is very strong, if we could control it I would appreciate, thanks a lot and looking forward to the new implementations of Pi-Pwn! You should probably add to your list of compatible devices that the 3 B is compatible, not just the 3 B +.

PS - Have you considered removing the Python option entirely? Looks like during instalation/setup via Putty majority of the time is spent with Python libraries, which I believe nobody will use anyway thanks to the benefits of the C++ version.

**Comment by stooged** [comment]
i have made changes to the install script so if the user selects no to the python option it does not bother with installing scapy and disables the option for python pppwn.
it will probably be removed in the future.


you can disable the leds in the config.txt.
put the sd card into your pc and find config.txt

add these lines to the bottom for the leds you want to disable

<hr>

### Disable Power LED (Red)
dtparam=pwr_led_activelow=off

<hr>

### Disable Activity LED (Green)
dtparam=act_led_trigger=none
dtparam=act_led_activelow=off

<hr>

### Disable LAN LEDs
dtparam=eth_led0=14
dtparam=eth_led1=14

**Comment by Doyle4** [comment]
Disable Power LED is:
dtparam=pwr_led_trigger=none
dtparam=pwr_led_activelow=off

Without dtparam=pwr_led_trigger=none the power LED will remain on.
