### ISSUE TITLE
Feature Addition/Enhancement: Back button in payloads screen

### ISSUE THREAD

**Issue by Sylntnyt** [stooged/PI-Pwn#70]
Being able to load payloads via USB from the RbPi is a great feature. To enhance it even more and make it more user friendly, the inclusion of a "Back" button on the "Payloads" screen (payloads.php) which takes the user back to the main screen (index.php) would be a great addition/enhancement rather than having to use other means/methods to get back to the main page.

**Comment by Doyle4** [comment]
I use the computer/Phone/Tablet built in web browsers back button

**Comment by Sylntnyt** [comment]
I do as well, I just know some people are the type to want a back button they can click/tap on somewhere on the page.

**Comment by stooged** [comment]
added a text link "back to config page"
