### ISSUE TITLE
Raspberry pi zero 2 w (End kernel panic)

### ISSUE THREAD

**Issue by Grmfly** [stooged/PI-Pwn#75]
After executing the code sudo apt update

sudo rm -f -r PI-Pwn
sudo systemctl stop pipwn

My pi reboot and get the error ( End kernel panic)
When I try to read the SD card in my laptop the rootfs can't be access 
(You can access this path if you are in Linux )
It will give you error or need to be format ot if you are in windows

**Comment by stooged** [comment]
reinstall the os i guess.
