### ISSUE TITLE
Remotely installing packages doesn't work

### ISSUE THREAD

**Issue by ttoille123** [stooged/PI-Pwn#80]
Every time i try to use either direct package installer or remote package sender v2 it doesn't ever get a reply back and either says timeout error or just doesn't work

**Comment by stooged** [comment]
if you are using programs to connect to the console you need to add the ports those programs use so the pi can forward them

**Comment by ttoille123** [comment]
Its just 9090 with goldhen? it just doesn't get a response from the console.

**Comment by stooged** [comment]
looking at [ps4-remote-pkg-sender](https://github.com/iref-use/ps4-remote-pkg-sender) you need to install [ps4_remote_pkg_installer](https://github.com/flatz/ps4_remote_pkg_installer) and that readme shows it is using port 12800

as far as i know port 9090 in goldhen is to load payloads not game packages

**Comment by ttoille123** [comment]
When i use it with the ps4 remote pkg it just says timeout error. When I use direct package installer and goldhen it's receives the payload but somehow my computer doesn't receive something that makes it install

**Comment by ttoille123** [comment]
I forgot this part but when I use remote package installer on the ps4 and direct package installer on the pc it works fine.
