### ISSUE TITLE
Setting the PS4 to rest mode seems to break the Pi-Pwn logic, LED confirmation/feedback.

### ISSUE THREAD

**Issue by MiToRMK** [stooged/PI-Pwn#82]
If during the initial setup you selected for the Pi to shutdown after a successful PPPwn, and you put your console to sleep, and then wake up the console later, the Pi will power on again. In fact looks like doing that messes up the Pi shutdown & PPPwn logic entirely.

Would it be possible to fix that so the Pi remains turned off after the PS4 wakes up from rest mode?

**I would like the Pi to turn on (and PPPwn the console) only if the PS4 is turned on from a total powered off state. That's because I want to preserve hardware and not generate unnecessary heat.**

Putting the console on rest mode after the Pi PPPwnd the console and shut itself off really breaks/makes the Pi confused because I couldn't get it to PPPwn after waking up, and in fact not even after a hard PS4 power off and power on.

EDIT - In order to get a PPPwn I had to disconnect the Pi cables, set up PPPoE settings, turn off console, plug the Pi cables on the PS4 again and boot the console. However the Pi still doesn't turn itself off anymore after the PPPwn (although I marked Y during the initial setup via Putty). I don't recommend to put the PS4 to sleep with the Pi plugged in, at least not with the current implementation, because doing so makes the auto-off Pi functionality not work anymore.

**Comment by MiToRMK** [comment]
As it turns out, putting the console on rest mode really breaks/makes the Pi confused because I couldn't get it to PPPwn after waking up, and in fact not even after a hard PS4 power off and power on.

**Comment by stooged** [comment]
try setting the rest mode to supply power to the usb ports so the pi stays powered while it rest mode.
if should keep the pi in the shutdown state

**Comment by MiToRMK** [comment]
> try setting the rest mode to supply power to the usb ports so the pi stays powered while it rest mode. if should keep the pi in the shutdown state

I think you missed the point, as "Supply Power to USB Ports" was checked this whole time.
