### ISSUE TITLE
Alpinelinux

### ISSUE THREAD

**Issue by zero13th** [stooged/PI-Pwn#85]
Hi I'm using alpinelinux with openRC.

could you fix this?
![image](https://github.com/stooged/PI-Pwn/assets/3038360/a9c061bd-b155-4ca0-abee-21ed8b17d3be)

**Comment by zero13th** [comment]
what I did:
1. change working directory = sed  -i 's|/boot/firmware/PPPwn/|/media/mmcblk0p1/PPPwn/|g' run.sh
2. using root account (no need for sudo) = sed  -i 's|sudo ||g' run.sh
run.sh with default config parameter.

manually poweroff command doesnot makes rpi off until I kill run.sh process

![image](https://github.com/stooged/PI-Pwn/assets/3038360/b91fc1b2-0ad3-45a0-815f-c4f7df701d0e)

**Comment by stooged** [comment]
there is a good chance a lot will be broken on other nix distros, i am only working around raspberry pi os lite and armbian cli/minimal.
