### ISSUE TITLE
PS4 pro model 7116B failing

### ISSUE THREAD

**Issue by bse4792** [stooged/PI-Pwn#9]
My PS4 Pro

updated to fw 11.00 from 10.5 on this i made a factory reset

i have tried this.

output from pi 3B is
waiting for connection
system 11.00
connected to eth0

then nothing happens for hrs

i have also tried the windows tool nothing happens

**Comment by LifeOfAScoob** [comment]
Same problem.

**Comment by stooged** [comment]
i have made some changes to deal with slower rpi models not starting the pppwn properly.
