### ISSUE TITLE
Second Ethernet Port for Pi (no WiFi)

### ISSUE THREAD

**Issue by Rocket200** [stooged/PI-Pwn#94]
Can I use a second Ethernet port on the Pi with your pi-pwn ? 

https://amzn.eu/d/9EDEyqL

go online and ftp work without WiFi !
is this possible or need changes ?

**Comment by stooged** [comment]
while it does work with 2 ethernet ports and no wifi i dont know about the pi hat you posted.

it should work but i dont know.

**Comment by Rocket200** [comment]
You know a other working second Ethernet work with PIs?

I get this adapter in 2 days than I can tell more…
