### ISSUE TITLE
Goldhen Load time

### ISSUE THREAD

**Issue by Doyle4** [stooged/PI-Pwn#95]
Was wondering if it would be possible to change this time value in the Web server?
I understand it has been delayed for reasons, but Id like to test different time values and how it affects the Jailbreak Process. 

Thanks again.

**Comment by stooged** [comment]
The delay is compiled into the stage 2 bin file.

The stage2 file here has no delay
https://github.com/SiSTR0/PPPwn

**Comment by Doyle4** [comment]
Amazing, thank you.
