### ISSUE TITLE
PS4 abruptly shuts down with no warning

### ISSUE THREAD

**Issue by TheHotRodJayden** [stooged/PI-Pwn#98]
Im on fw version 11.00. When i get to the part that says a DNS server cant be found, after a few failed to connect errors the console just dies. No warning at all.

**Comment by TheHotRodJayden** [comment]
Im also using a raspberry pi 4 B

**Comment by Doyle4** [comment]
Should say LAN Cable disconnected then Can't connect to network.
Check your PS4 Internet settings are correct.

**Comment by TheHotRodJayden** [comment]
> Should say LAN Cable disconnected then Can't connect to network. Check your PS4 Internet settings are correct.

My settings are correct. username : ppp password: ppp and the rest "automatic, automatic, do not use"

**Comment by TheHotRodJayden** [comment]
Does it matter when you connect the LAN cable? Ive been connecting it before turning on the console.

**Comment by stooged** [comment]
you will cause it to kernel panic by messing with the network settings on the console.
you dont do internet tests or play with the network settings.

you setup the connection 1 time, wired>PPPOE. user pass = ppp, automatic, automatic, do not use

after that you should never need to go into the network settings unless you want to change the information etc

you leave the pi connected to the lan cable and boot both the console and pi and the pi will find the console and start working on it.

certain ps4 models will always panic no matter what you do, some of them are posted here https://x.com/notnotzecoxao/status/1791848326825959611
